"""empty message

Revision ID: 75808b26a837
Revises: 
Create Date: 2020-04-09 20:37:40.021729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75808b26a837'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Actor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.CHAR(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ActorMovie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movieId', sa.Integer(), nullable=True),
    sa.Column('actorId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actorId'], ['Actor.id'], ),
    sa.ForeignKeyConstraint(['movieId'], ['Movie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ActorMovie')
    op.drop_table('Movie')
    op.drop_table('Actor')
    # ### end Alembic commands ###
